FORMAT: 1A
HOST: http://sandbox.api.colisweb.com

# Colisweb API v4

Ce document décrit les points d'entrée, appelés **endpoints** dans la suite de ce document, de l'API que fournit **Colisweb** ainsi que les workflows d'utilisations de cette API qui permettent d'effectuer certaines actions complexes.

# Autorisations d'accès

Une clé API est nécéssaire pour l'utilisation de cette API.   
Afin d'obtenir une clé, vous devez effectuer une demande par mail à support@colisweb.com.

# Environnements

Deux environnements sont disponibles :  

**sandbox** : Environnement "bac à sable" pour vos tests avant mise en production.   
https://sandbox.api.colisweb.com

**production** : Après validation des tests en sandbox.   
https://api.colisweb.com

# URL d'appels

L'URL d'appel à l'API est:   
https://[sandbox.]api.colisweb/4/<strong>end_point</strong>

**end_point** = Méthodes décrites dans ce document

# Codes d'erreurs

| Error name                | HTTP Status       | Description                       |
| ------------------------  | ----------------  | --------------------------------- |
| wrong_api_key             | 401 Unauthorized  | Clé API manquante / inconnue      |
| missing_parameters        | 400 Bad Request   | Il manque des paramètres          |
| fail_to_confirm_delivery  | 400 Bad Request   | Le commande de livraison a échoué |
| no_delivery_options       | 404 not found     | Aucune disponibilité de livraison |
| missing_delivery          | 404 not found     | Numéro de commande inconnue       |

# Entités en entrée

## Introduction

Nous gérons des **livraisons** partant d'un **point A** (point de retrait) et arrivant à un **point B** (point de livraison).   
Nous avons formalisé ces notions de **livraisons** et de **points** dans des types de données spécifiques.

Voici un schéma UML des entités décrites ci-dessous.   

![alt text](https://photos-5.dropbox.com/t/2/AAA5du9CNqQyOgj7LI5yVEfP0XvJ8ygSmqYD6vSBTx0K5A/12/8290481/png/32x32/1/_/1/2/apiv4_entities_v3.png/EJPblQYYjYkrIAEgAigB/683o8fd9fePEBZxdLwOJycwUXN5g2UTcY48GC0zoAq0?size=1280x960&size_mode=2 "UML des entitées de l'API")

## L'entité "Point"

+ Un **Point** posséde deux attribut qui définissent ce que ce point représente:
    + L'attribut ```point_type``` qui peut prendre les valeurs suivantes :
        + ```"PICKUP"``` : signifie que le **Point** représente un point de retrait.
        + ```"SHIPPING"``` : signifie que le **Point** représente un point de livraison.
    + L'attribut ```address_type``` qui peut prendre les valeurs suivantes :
        + ```"STORE"``` : signifie que le **Point** représente un magasin.
        + ```"CONSUMER"``` : signifie que le **Point** représente l'adresse d'une personne. // TODO: trouver un meilleur terme que "personne"


+ Un **Point** est composé d'une **Location** : l'endroit physique qui servira de point de retrait ou de livraison.   

## L'entité "Location"

Une **Location** est un type abstrait qui possède trois spécialisations concrétes:
+ Une **Town** : représente une zone définit par un code postal.   
Utile lorsque qu'une adresse précise n'est pas requise.
+ Une **Address** : adresse précise quelconque. Celle du client qui souhaite se faire livrer, par exemple.   
+ Un **Store** : un de vos magasins, si nous avons référencé vos magasins.

## L'entité "Town"

Une **Town** est composé de l'attribut suivant :

+ ```postal_code``` *(required, string)*: le code postal de la ville.

## L'entité "Address"

Une **Address** est composée des attributs suivants : 

```society``` *(optional, string)* : Société.   
```first_name``` *(optional, string)* : Prénom.   
```last_name``` *(required, string)* : Nom.   
```email``` *(required, string)* : Email.   
```primary_phone``` *(required, string)* : Numéro de téléphone primaire.   
```secondary_phone``` *(optional, string)* : Numéro de téléphone secondaire.   
```line1``` *(required, string)* : Adresse de livraison.   
```line2``` *(optional, string)* : Complément d'adresse.   
```additional_informations``` *(optional, string)* : Informations supplémentaire (digicode, etc.)   
```zip_code``` *(required, string)* : Code postal.   
```city``` *(required, string)* : Ville.   
```country``` *(required, string)* : Pays.   
```send_delivery_statuses``` *(optional, boolean)* : Envoyer les statuts de livraison par sms/email au consommateur.   
    ```true``` par défaut, dépend cependant de la configuration globale au niveau de l'enseigne lors de la contractualisation avec Colisweb.   
```send_survey``` *(optional, boolean)* : Envoyer  l'enquête de satisfaction au consommateur.   
    ```true``` par défaut, dépend cependant de la configuration globale au niveau de l'enseigne lors de la contractualisation avec Colisweb.   

## L'entité "Store"

Nous enregistrons les informations de vos magasins dans notre système au moment de la signature du contrat.   
Seul l'identifiant unique de ce magasin est donc nécessaire pour que nous puissions l'identifier.   

Un **Store** est composé de l'attribut suivant : 

+ **store_code** *(required, string)* : Code magasin.   

## L'entité "Delivery"

TODO Jules

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "order_ref": "R10390",
                "order_id": "987663"
                "command_status": "CANCELED",
                "transporter_status": "CANCELED",
                "sender_status": "CANCELED",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                },
                "points": [
                    {
                        "point_type": "PICKUP",
                        "address": {
                            "society": "Twelve factors & C",
                            "first_name": "Helmout",
                            "last_name": "Ardelpik",
                            "email": "helmoutardelpik@gmail.com",
                            "primary_phone": "0694385693",
                            "secondary_phone": "0354678942",
                            "line1": "165, avenue des champs Elysées",
                            "line2": "Batiment Leblanc",
                            "additional_informations": "Digicode B345, 3 éme etage",
                            "zip_code": "75001",
                            "city": "Paris",
                            "country": "France",
                            "send_delivery_statuses": true,
                            "send_survey": true
                        }
                    },
                    {
                        "point_type": "SHIPPING"
                        "store" {
                            "store_code": "100002"
                        }
                    }
                ],
                "packets": [
                    {
                        "product_description": "Ipad mini",
                        "weight": 1.55,
                        "height": 14.55,
                        "length": 15.55,
                        "width": 16.55
                    },
                    {
                        "product_description": "Iphone",
                        "weight": 2.55,
                        "height": 24.55,
                        "length": 25.55,
                        "width": 26.55
                    }
                ]
            }
        }

# Entités en sortie

# Types de livraison disponibles

## Introduction

Via notre API, vous êtes en mesure de commander **quatres types de livraisons** :

+ **B2B** (exemple : réapprovisionnement entre magasins)
+ **B2C** (exemple : livraison d'un client final)
+ **C2B** (exemple : retour magasin)
+ **C2C** (exemple : livraison entres deux adresses quelconques)

Nous identifions le type de livraison que vous commandez en regardant quels types d'entités **Location** vous nous envoyez dans vos paramètres de requêtes.

## Exemple de paramètre de requête pour du B2B

```
{
    ...
    "points": [
        {
            "point_type": "PICKUP",
            "store" {
                "store_code": "100001"
            }
        },
        {
            "point_type": "SHIPPING"
            "store" {
                "store_code": "100002"
            }
        }
    ]
    ...
}
```

## Exemple de paramètre de requête pour du B2C

```
{
    ...
    "points": [
        {
            "point_type": "PICKUP",
            "store" {
                "store_code": "100001"
            }
        },
        {
            "point_type": "SHIPPING",
            "address": {
                "society": "Twelve factors & C",
                "first_name": "Helmout",
                "last_name": "Ardelpik",
                "email": "helmoutardelpik@gmail.com",
                "primary_phone": "0694385693",
                "secondary_phone": "0354678942",
                "line1": "165, avenue des champs Elysées",
                "line2": "Batiment Leblanc",
                "additional_informations": "Digicode B345, 3 éme etage",
                "zip_code": "75001",
                "city": "Paris",
                "country": "France",
                "send_delivery_statuses": true,
                "send_survey": true
            }
        }
    ]
    ...
}
```

## Exemple de paramètre de requête pour du C2B

```
{
    ...
    "points": [
        {
            "point_type": "PICKUP",
            "address": {
                "society": "Twelve factors & C",
                "first_name": "Helmout",
                "last_name": "Ardelpik",
                "email": "helmoutardelpik@gmail.com",
                "primary_phone": "0694385693",
                "secondary_phone": "0354678942",
                "line1": "165, avenue des champs Elysées",
                "line2": "Batiment Leblanc",
                "additional_informations": "Digicode B345, 3 éme etage",
                "zip_code": "75001",
                "city": "Paris",
                "country": "France",
                "send_delivery_statuses": true,
                "send_survey": true
            }
        },
        {
            "point_type": "SHIPPING"
            "store" {
                "store_code": "100002"
            }
        }
    ]
    ...
}
```

## Exemple de paramètre de requête pour du C2C

```
{
    ...
    "points": [
        {
            "point_type": "PICKUP",
            "address": {
                "society": "",
                "first_name": "Alan",
                "last_name": "Turing",
                "email": "alan.turing@gmail.com",
                "primary_phone": "0624243624",
                "secondary_phone": "",
                "line1": "125 rue de Vaugirard",
                "line2": "",
                "additional_informations": "",
                "zip_code": "75015",
                "city": "Paris",
                "country": "France",
                "send_delivery_statuses": true,
                "send_survey": true
            }
        },
        {
            "point_type": "SHIPPING",
            "address": {
                "society": "Twelve factors & C",
                "first_name": "Helmout",
                "last_name": "Ardelpik",
                "email": "helmoutardelpik@gmail.com",
                "primary_phone": "0694385693",
                "secondary_phone": "0354678942",
                "line1": "165, avenue des champs Elysées",
                "line2": "Batiment Leblanc",
                "additional_informations": "Digicode B345, 3 éme etage",
                "zip_code": "75001",
                "city": "Paris",
                "country": "France",
                "send_delivery_statuses": true,
                "send_survey": true
            }
        }
    ]
    ...
}
```

# Fuseaux Horaires

Toutes les dates de cette API sont en UTC, au format ISO 8601 avec indication de fuseau horaire.   
Exemple : 
```
2015-04-22T12:00:00+00:00
```

TODO Jules


# Group Gestion et commande de livraisons

# Obtenir les options de livraison disponibles [/deliveries/options]

Permet de récupérer les options de livraisons disponibles.

## Paramètres de requête

+ **api_key** *(required, string)* : Clé API Colisweb.
+ **slot_size** *(optional, integer)* : Taille de la plage de livraison demandée (en minutes).   
Exemple : 120 pour une livraison en 2h.   
Ce paramètre permet d'écraser la valeur par défaut de Colisweb.
+ **points** *(required, array of <strong>Points</strong>)* : Informations sur les points de retrait et de livraison.    
Pour que la demande soit valide, il faut absolument que ce tableau contiennent deux entités **Point**, l'une ayant comme valeur de **point_type** ```"PICKUP"``` et l'autre  ```"SHIPPING"```.    
*Remarque* : **Pour ce endpoint uniquement**, dans le cas d'une **Address** le **zip_code** suffit.
+ **packets** *(required, array of hashes)* : Informations sur les colis.
  + **length** *(required, float)* : Longueur du colis (en cm).
  + **width** *(required, float)* : largeur du colis (en cm).
  + **height** *(required, float)* : hauteur du colis (en cm).
  + **weight** *(required, float)* : poids du colis (en grammes).

## Contenu de la réponse

+ **now** *(hash)* : Disponibilité de l'offre "instantanée".
  + **available** *(boolean)* : Livraison "instantanée" disponible ou non.
  + **slot_size** *(integer)* : Taille du créneau horaire en minutes de la livraison "instantanée" (en minutes).
  + **price** *(float)* : Coût HT de la livraison "instantanée" (en euro).
+ **planned** *(array of hashes)* : Plages horaires de livraison sur rendez-vous.
  + **starts_at** *(datetime UTC)* : Début d'un créneau horaire.
  + **ends_at** *(datetime UTC)* : Fin d'un créneau horaire.
  + **slot_size** *(integer)* : Taille du créneau horaire (en minutes).
  + **price** *(float)* : Coût HT de la livraison dans ce créneau (en euro).

## POST

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "slot_size": 120,
            "points": [
                {
                   "point_type": "PICKUP",
                   "address": {
                       "zip_code": "75012"                       
                   }
                },
                {
                    "point_type": "SHIPPING",
                    "store": {
                        "store_code": "100001"                        
                    }
                }
            ],
            "packets": [
                {
                    "weight": 1.55,
                    "height": 14.55,
                    "length": 15.55,
                    "width": 16.55
                },
                {
                    "weight": 2.55,
                    "height": 24.55,
                    "length": 25.55,
                    "width": 26.55
                }
            ]
        }

+ Response 200 (application/json)

        {
            "now" : {
                "available": true,
                "slot_size": 120,
                "price" : 5.55
            },
            "planned" : [
                {
                    "starts_at": "2015-04-22T10:00:00+00:00",
                    "ends_at": "2015-04-22T12:00:00+00:00",
                    "slot_size": 120,
                    "price" : 5.55
                },
                {
                    "starts_at": "2015-04-22T12:00:00+00:00",
                    "ends_at": "2015-04-22T14:00:00+00:00",
                    "slot_size": 120,
                    "price" : 5.55
                },
                {
                    "starts_at": "2015-04-22T14:00:00+00:00",
                    "ends_at": "2015-04-22T15:00:00+00:00",
                    "slot_size": 60,
                    "price" : 5.55
                },
                {
                    "starts_at": "2015-04-23T10:00:00+00:00",
                    "ends_at": "2015-04-23T12:00:00+00:00",
                    "slot_size": 120,
                    "price" : 5.55
                },
                {
                    "starts_at": "2015-04-23T12:00:00+00:00",
                    "ends_at": "2015-04-23T14:00:00+00:00",
                    "slot_size": 120,
                    "price" : 5.55
                },
                {
                    "starts_at": "2015-04-23T14:00:00+00:00",
                    "ends_at": "2015-04-23T15:00:00+00:00",
                    "slot_size": 60,
                    "price" : 5.55
                }
            ]
        }

# Pré-commander une livraison [/deliveries/book]

Permet d'effectuer une pré-commande de livraison.   
Cette pré-commande sera ensuite à confirmer dans la méthode [Finaliser une commande de livraison](#reference/gestion-et-commande-de-livraisons/finaliser-une-commande-de-livraison).

## Paramètres de requête

+ **api_key** *(required, string)* : Clé API Colisweb
+ **starts_at** *(required, datetime UTC)* : Date et heure de début de la plage de livraison.   
Pour passer une demande en mode "Instantané", passez la date / heure actuelle.   
Vous pouvez passer la valeur que vous souhaitez, cependant seuls les valeurs fournies par le endpoint [```/deliveries/options```](#reference/deliveries/obtenir-les-options-de-livraison-disponbiles) garantissent une réponse positive de l'API.   
+ **slot_size** *(required, integer)* : Taille de la plage de livraison demandée (en minutes).   
Vous pouvez passer la valeur que vous souhaitez, cependant seuls les valeurs fournies par le endpoint [```/deliveries/options```](#reference/deliveries/obtenir-les-options-de-livraison-disponbiles) garantissent une réponse positive de l'API.
+ **points** *(required, array of <strong>Points</strong>)* : Informations sur les points de retrait et de livraison.    
Pour que la demande soit valide, il faut absolument que ce tableau contiennent deux entités **Point**, l'une ayant comme valeur de **point_type** ```"PICKUP"``` et l'autre  ```"SHIPPING"```.    
+ **packets** *(required, array of hashes)* : Informations sur les colis
  + **product_description** *(optional, string)* : Typologie/dénomination du/des produits contenue dans ce "packet".   
  Exemple : "micro-onde".
  + **length** *(required, float)* : Longueur du colis (en cm).
  + **width** *(required, float)* : Largeur du colis (en cm).
  + **height** *(required, float)* : Hauteur du colis (en cm).
  + **weight** *(required, float)* : Poids du colis (en grammes).

## Contenu de la réponse

+ **delivery** *(hash)* : Informations sur la commande créée
    + **command_id** *(string)* - Identifiant de la commande créée.   
    **Cet identifiant vous sera nécessaire, notamment, pour effectuer la confirmation de la commande.**
    + **command_status**: ```"PRE_ORDERED"```
    + **transporter_status**: ```"IDLE"```
    + **sender_status**: ```"IDLE"```
    + **slot** *(hash)* : Informations de la plage horaire commandée.
      + **starts_at** *(datetime UTC)* : Début d'un créneau horaire.
      + **ends_at** *(datetime UTC)* : Fin d'un créneau horaire.
      + **slot_size** *(integer)* : Taille du créneau horaire (en minutes).
      + **price** *(float)* : Coût HT de la livraison (en euro).
  
## Exemple de pré-commande de livraison B2B [POST]

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "starts_at": "2015-04-22T16:00:00+00:00",
            "slot_size": 120,
            "points": [
                {
                    "point_type": "PICKUP",
                    "store": {
                        "store_code": "100001"
                    }
                },
                {
                    "point_type": "SHIPPING",
                    "store": {
                        "store_code": "100002"
                    }
                }
            ],
            "packets": [
                {
                    "product_description": "Ipad mini",
                    "weight": 1.55,
                    "height": 14.55,
                    "length": 15.55,
                    "width": 16.55
                },
                {
                    "product_description": "Iphone",
                    "weight": 2.55,
                    "height": 24.55,
                    "length": 25.55,
                    "width": 26.55
                }
            ]
        }

+ Response 201 (application/json)

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "PRE_ORDERED",
                "transporter_status": "IDLE",
                "sender_status": "IDLE",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                }
            }
        }

## Exemple de pré-commande de livraison B2C [POST]

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "starts_at": "2015-04-22T16:00:00+00:00",
            "slot_size": 120,
            "points": [
                {
                    "point_type": "PICKUP",
                    "store": {
                        "store_code": "100001"
                    }
                },
                {
                    "point_type": "SHIPPING",
                    "address": {
                        "society": "Twelve factors & C",
                        "first_name": "Helmout",
                        "last_name": "Ardelpik",
                        "email": "helmoutardelpik@gmail.com",
                        "primary_phone": "0694385693",
                        "secondary_phone": "0354678942",
                        "line1": "165, avenue des champs Elysées",
                        "line2": "Batiment Leblanc",
                        "additional_informations": "Digicode B345, 3 éme etage",
                        "zip_code": "75001",
                        "city": "Paris",
                        "country": "France",
                        "send_delivery_statuses": true,
                        "send_survey": true
                    }
                }
            ],
            "packets": [
                {
                    "product_description": "Ipad mini",
                    "weight": 1.55,
                    "height": 14.55,
                    "length": 15.55,
                    "width": 16.55
                },
                {
                    "product_description": "Iphone",
                    "weight": 2.55,
                    "height": 24.55,
                    "length": 25.55,
                    "width": 26.55
                }
            ]
        }

+ Response 201 (application/json)

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "PRE_ORDERED",
                "transporter_status": "IDLE",
                "sender_status": "IDLE",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                }
            }
        }

## Exemple de pré-commande de livraison C2B [POST]

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "starts_at": "2015-04-22T16:00:00+00:00",
            "slot_size": 120,
            "points": [
                {
                    "point_type": "PICKUP",
                    "address": {
                        "society": "Twelve factors & C",
                        "first_name": "Helmout",
                        "last_name": "Ardelpik",
                        "email": "helmoutardelpik@gmail.com",
                        "primary_phone": "0694385693",
                        "secondary_phone": "0354678942",
                        "line1": "165, avenue des champs Elysées",
                        "line2": "Batiment Leblanc",
                        "additional_informations": "Digicode B345, 3 éme etage",
                        "zip_code": "75001",
                        "city": "Paris",
                        "country": "France",
                        "send_delivery_statuses": true,
                        "send_survey": true
                    }
                },
                {
                    "point_type": "SHIPPING",
                    "store": {
                        "store_code": "100001"
                    }
                }
            ],
            "packets": [
                {
                    "product_description": "Ipad mini",
                    "weight": 1.55,
                    "height": 14.55,
                    "length": 15.55,
                    "width": 16.55
                },
                {
                    "product_description": "Iphone",
                    "weight": 2.55,
                    "height": 24.55,
                    "length": 25.55,
                    "width": 26.55
                }
            ]
        }

+ Response 201 (application/json)

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "PRE_ORDERED",
                "transporter_status": "IDLE",
                "sender_status": "IDLE",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                }
            }
        }

## Exemple de pré-commande de livraison C2C [POST]

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "starts_at": "2015-04-22T16:00:00+00:00",
            "slot_size": 120,
            "points": [
                {
                    "point_type": "PICKUP",
                    "address": {
                        "society": "",
                        "first_name": "Alan",
                        "last_name": "Turing",
                        "email": "alan.turing@gmail.com",
                        "primary_phone": "0624243624",
                        "secondary_phone": "",
                        "line1": "125 rue de Vaugirard",
                        "line2": "",
                        "additional_informations": "",
                        "zip_code": "75015",
                        "city": "Paris",
                        "country": "France",
                        "send_delivery_statuses": true,
                        "send_survey": true
                    }
                },
                {
                    "point_type": "SHIPPING",
                    "address": {
                        "society": "Twelve factors & C",
                        "first_name": "Helmout",
                        "last_name": "Ardelpik",
                        "email": "helmoutardelpik@gmail.com",
                        "primary_phone": "0694385693",
                        "secondary_phone": "0354678942",
                        "line1": "165, avenue des champs Elysées",
                        "line2": "Batiment Leblanc",
                        "additional_informations": "Digicode B345, 3 éme etage",
                        "zip_code": "75001",
                        "city": "Paris",
                        "country": "France",
                        "send_delivery_statuses": true,
                        "send_survey": true
                    }
                }
            ],
            "packets": [
                {
                    "product_description": "Ipad mini",
                    "weight": 1.55,
                    "height": 14.55,
                    "length": 15.55,
                    "width": 16.55
                },
                {
                    "product_description": "Iphone",
                    "weight": 2.55,
                    "height": 24.55,
                    "length": 25.55,
                    "width": 26.55
                }
            ]
        }

+ Response 201 (application/json)

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "PRE_ORDERED",
                "transporter_status": "IDLE",
                "sender_status": "IDLE",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                }
            }
        }

# Finaliser une commande de livraison [/deliveries/{delivery_id}/confirm]

Une fois que vous avez pré-commandé une livraison et que l'API vous a retourné le **command_id** de votre commande, vous devez la confirmer pour finaliser votre commande.

***Attention*** : Un maximum de **15 minutes** est autorisé entre la pré-commande et la confirmation de la commande.   
Au delà, une erreur **delivery_has_expired** est renvoyée.

## Paramètres de requête

+ **api_key** *(required, string)* : Clé API Colisweb
+ **order_ref** *(required if not C2C, string)* : Référence commande de votre plateforme   
(permet au transporteur d'identifier le colis en boutique).
+ **order_id** *(optional, string)* : identifiant commande interne à votre plateforme.

## Contenu de la réponse

+ **delivery** *(<strong>Delivery</strong>)* : Informations sur la livraison commandé

## PUT

+ Parameters
    + delivery_id - Identifiant de la livraison obtenue lors de la pré-commande

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013",
            "order_ref": "R10390",
            "order_id": "987663"
        }

+ Response 200 (application/json)
        
        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "CONFIRMED",
                "transporter_status": "IDLE",
                "sender_status": "PREPARING",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                },
                "order_ref": "R10390",
                "order_id": "987663"
            }
        }
        


# Annuler une livraison [/deliveries/{delivery_id}/cancel]

Vous pouvez annuler une livraison jusqu'à un certain stade d'avancement de celle-ci.   
Par exemple, si la livraison est au statut "livrée", elle ne sera pas annulable.

## Paramètres de requête

+ **api_key** *(required, string)* : Clé API Colisweb

## Contenu de la réponse

+ **delivery** *(<strong>Delivery</strong>)* : Informations sur la livraison commandé


## PUT

+ Parameters
    + delivery_id - Identifiant de la livraison donnée lors de la pré-commande.

+ Request (application/json)

        {
            "api_key": "3025688655a161aeb167b7b33f03c013"
        }

+ Response 200

        {
            "delivery": {
                "command_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
                "command_status": "CANCELED",
                "transporter_status": "CANCELED",
                "sender_status": "CANCELED",
                "slot": {
                    "starts_at": "2015-04-22T16:00:00+00:00",
                    "ends_at": "2015-04-22T18:00:00+00:00",
                    "slot_size": 120,
                    "price": 5.55
                },
                "order_ref": "R10390",
                "order_id": "987663"
            }
        }

+ Response 400
