FORMAT: 1A
HOST: http://sandbox.api.colisweb.com

# Colisweb API v4

Ce document décrit les endpoints de l'API que fournit **Colisweb** ainsi que les workflows d'utilisations de cette API qui permettent d'effectuer certaines actions complexes.

## Autorisations d'accès
Une clé API est nécéssaire pour l'utilisation de cette API.
Afin d'obtenir une clé, vous devez effectuer une demande par mail à support@colisweb.com.

## Environnements
Deux environnements sont disponibles :  

**sandbox** : Environnement "bac à sable" pour vos tests avant mise en production.
http://sandbox.api.colisweb.com

**production** : Après validation des tests en sandbox.
http://api.colisweb.com

## URL d'appels
L'url d'appel à l'API est:   
**https://[sandbox.]api.colisweb/4/end_point**

**end_point** = Méthodes décrites dans ce document

## Codes d'erreurs

<table>
  <tr><th>Error name</th><th>HTTP Status</th><th>Description</th></tr>
  <tr>
     <td>wrong_api_key</td>
     <td>401 Unauthorized</td>
     <td>Clé API manquante / inconnue</td>
  </tr>
  <tr>
     <td>missing_parameters</td>
     <td>400 Bad Request</td>
     <td>Il manque des paramètres</td>
  </tr>
  <tr>
     <td>fail_to_confirm_delivery</td>
     <td>400 Bad Request</td>
     <td>Le commande de livraison a échoué</td>
  </tr>
  <tr>
     <td>no_delivery_options</td>
     <td>404 not found</td>
     <td>Aucune disponibilité de livraison</td>
  </tr>
  <tr>
     <td>missing_delivery</td>
     <td>404 not found</td>
     <td>Numéro de commande inconnue</td>
  </tr>
</table>

# Group Deliveries

## Obtenir les options de livraison disponbiles [/deliveries/options]

Permet de récupérer les options de livraisons disponibles par rapport à différents paramètres.

### Paramètres de requête

+ **api_key** *(required, string)* : Clé API Colisweb.
+ **slot_size** *(optional, integer)* : Taille de la plage de livraison demandée (en minutes).   
Exemple : 120 pour une livraison en 2h.   
Ce paramètre permet d'écraser la valeur par défaut de Colisweb.
+ **pickup_point** *(required, hash)* : Informations du point de retrait.
  + **zip_code** *(required, string)* : Code postal du point de retrait.
+ **shipping_point** *(required, hash)* : Informations du point de livraison.
  + **zip_code** *(required, string)* : Code postal du point de livraison.
+ **packets** *(required, array of hashes)* : Informations sur les colis.
  + **length** *(required, float)* : Longueur du colis (en cm).
  + **width** *(required, float)* : largeur du colis (en cm).
  + **height** *(required, float)* : hauteur du colis (en cm).
  + **weight** *(required, float)* : poids du colis (en grammes).


### Contenu de la réponse

+ **now** *(hash)* : Disponibilité de l'offre "instantanée.
  + **available** *(boolean)* : Livraison "instantanée" disponible ou non.
  + **slot_size** *(integer)* : Taille du créneau horaire en minutes de la livraison "instantanée" (en minutes).
  + **price** *(integer)* : Coût HT de la livraison "instantanéé" (en euro).
+ **planned** *(array of hashes)* : Plages horaires de livraison sur rendez-vous.
  + **starts_at** *(datetime UTC)* : Début d'un créneau horaire.
  + **ends_at** *(datetime UTC)* : Fin d'un créneau horaire.
  + **slot_size** *(integer)* : Taille du créneau horaire (en minutes).
  + **price** *(float)* : Coût HT de la livraison dans ce créneau (en euro).

### POST

+ Request (application/json)

{
  "api_key": "3025688655a161aeb167b7b33f03c013",
  "slot_size": 120,
  "pickup_point": {
    "zip_code": "75012"
  },
  "shipping_point": {
    "zip_code": "75001"
  },
  "packets": [
    {
      "weight": 1.55,
      "height": 14.55,
      "length": 15.55,
      "width": 16.55
    },
    {
      "weight": 2.55,
      "height": 24.55,
      "length": 25.55,
      "width": 26.55
    }
  ]
}

+ Response 200 (application/json)

{
  "response" : {
    "now" : {
      "available": true,
      "slot_size": 120,
      "price" : 5.55
    },
    "planned" : [
      {
        "starts_at": "2015-04-22T10:00:00+00:00",
        "ends_at": "2015-04-22T12:00:00+00:00",
        "slot_size": 120,
        "price" : 5.55
      },
      {
        "starts_at": "2015-04-22T12:00:00+00:00",
        "ends_at": "2015-04-22T14:00:00+00:00",
        "slot_size": 120,
        "price" : 5.55
      },
      {
        "starts_at": "2015-04-22T14:00:00+00:00",
        "ends_at": "2015-04-22T15:00:00+00:00",
        "slot_size": 60,
        "price" : 5.55
      },
      {
        "starts_at": "2015-04-23T10:00:00+00:00",
        "ends_at": "2015-04-23T12:00:00+00:00",
        "slot_size": 120,
        "price" : 5.55
      },
      {
        "starts_at": "2015-04-23T12:00:00+00:00",
        "ends_at": "2015-04-23T14:00:00+00:00",
        "slot_size": 120,
        "price" : 5.55
      },
      {
        "starts_at": "2015-04-23T14:00:00+00:00",
        "ends_at": "2015-04-23T15:00:00+00:00",
        "slot_size": 60,
        "price" : 5.55
      }
    ]
  }
}

## Commander une livraison [/deliveries/book]

Permet d'effectuer une pré-commande de livraison.   
Cette pré-commande sera ensuite à confirmer dans la méthode "Confirmer une livraison".

+ **stores_code** *(optional, string)* : Code magasin.   
Si rempli, alors le point retrait sera considéré comme un magasin.   
Si vide, alors le point de retrait sera considéré comme une adresse quelconque. (L'adresse du client que vous voulez livrer par exemple).
Attention: Pour que cette 
+ **society** (optional, string) : Société.
+ **first_name** (optional, string) : Prénom.
+ **last_name** (required, string) : Nom.
+ **email** (required, string) : Email.
+ **primary_phone** (required, string) : Numéro de téléphone primaire.
+ **secondary_phone** (optional, string) : Numéro de téléphone secondaire.
+ **line1** (required, string) : Adresse de livraison.
+ **line2** (optional, string) : Complément d'adresse.
+ **additional_informations** (optional, string) : Informations supplémentaire (digicode, etc.)
+ **zip_code** (required, string) : Code postal.
+ **city** (required, string) : Ville.
+ **country** (required, string) : Pays.
+ **send_delivery_statuses** (optional, Boolean) : Envoyer les statuts de livraison par sms/email au consommateur
    + True par défaut, dépend cependant de la configuration globale au niveau de l'enseigne lors de la contractualisation avec Colisweb.
+ **send_survey** (optional, Boolean) : Envoyer  l'enquête de satisfaction au consommateur
    + True par défaut, dépend cependant de la configuration globale au niveau de l'enseigne lors de la contractualisation avec Colisweb.


**Les paramètres de requête sont les suivants** :
+ **api_key** *(required, string)* : Clé API Colisweb
+ **starts_at** *(required, datetime UTC)* : Date et heure de début de la plage de livraison.   
Pour passer une demande en mode "Instantané", passez la date / heure actuelle.   
Vous pouvez passer la valeur que vous souhaitez, cependant seuls les valeurs fournies par le endpoint [```/deliveries/options```](#reference/deliveries/obtenir-les-options-de-livraison-disponbiles) garantissent une réponse positive de l'API.   
+ **slot_size** *(required, integer)* : Taille de la plage de livraison demandée (en minutes).   
Vous pouvez passer la valeur que vous souhaitez, cependant seuls les valeurs fournies par le endpoint [```/deliveries/options```](#reference/deliveries/obtenir-les-options-de-livraison-disponbiles) garantissent une réponse positive de l'API.
+ **pickup_point** *(required, **Address**)* : Informations sur le point de retrait.
+ **shipping_point** *(required, **Address**)* : Informations sur le point de livraison.
+ **package** *(required, hash)* : Informations sur le colis.
  + **products_description** *(optional, string)* : Typologie / dénomination des produits.   
  Exemple : "micro-onde".
  + **packets** *(required, array of hashes)* : Informations sur les colis
    + **length** *(required, float)* : Longueur du colis (en cm).
    + **width** *(required, float)* : Largeur du colis (en cm).
    + **height** *(required, float)* : Hauteur du colis (en cm).
    + **weight** *(required, float)* : Poids du colis (en grammes).

**La réponse contiendra les informations suivantes** :

+ **delivery_id** *(string)* - Identifiant de la commande créée.   
**Cet identifiant vous sera nécessaire pour effectuer la confirmation de la commande.**
+ **slot** *(hash)* : Informations de la plage horaire commandée.
  + **starts_at** *(datetime UTC)* : Début d'un créneau horaire.
  + **ends_at** *(datetime UTC)* : Fin d'un créneau horaire.
  + **slot_size** *(integer)* : Taille du créneau horaire (en minutes).
  + **price** *(float)* : Coût HT de la livraison (en euro).
  
### POST

+ Request (application/json)

{
  "api_key": "3025688655a161aeb167b7b33f03c013",
  "starts_at": "2015-04-22T16:00:00+00:00",
  "slot_size": 120,
  "pickup_point": {
    "store_code": "100001",
  },
  "shipping_point": {
    "society": "Twelve factors & C",
    "first_name": "Helmout",
    "last_name": "Ardelpik",
    "email": "helmoutardelpik@gmail.com",
    "primary_phone": "0694385693",
    "secondary_phone": "0354678942",
    "line1": "165, avenue des champs Elysées",
    "line2": "Batiment Leblanc",
    "additional_informations": "Digicode B345, 3 éme etage, accès parking",
    "zip_code": "75001",
    "city": "Paris",
    "country": "France",
    "send_delivery_statuses": true,
    "send_survey": true
  },
  "packaging": {
    "products_description": "Ipad mini",
    "packets": [
      {
        "weight": 1.55,
        "height": 14.55,
        "length": 15.55,
        "width": 16.55
      },
      {
        "weight": 2.55,
        "height": 24.55,
        "length": 25.55,
        "width": 26.55
      }
    ]
  }
}

+ Response 201 (application/json)

{
  "response":{
    "delivery_id": "03355b96-7195-411a-9c3f-3a6a4b6997ce",
    "slot" : {
      "starts_at": "2015-04-22T16:00:00+00:00",
      "ends_at": "2015-04-22T18:00:00+00:00",
      "slot_size": 120,
      "price": 5.55
    }
  }
}

## confirm-delivery [/3/confirm_delivery]

Confirme la commande créée via la methode "book-delivery".

***Attention*** : Un maximum de 15 minutes est autorisé entre l'appel au book-delivery et cet appel.
Au delà une erreur "delivery_has_expired" est renvoyée.

**Exemple d'utilisation :**

Aprés la validation du paiement.

**Un confirm-delivery renvoie les attributs suivants** :

+ ***confirmed*** (boolean) : la valeur "True" indique que la livraison a bien été prise en compte.

**Les paramètres de requête sont les suivants** :

+ **api_key** (required, string) : Clé api client colisweb
+ **delivery_id** (required, integer) : ID commande colisweb récupérée lors de l'appel à la méthode book-delivery
+ **order_ref** (required, string) : Référence commande de votre plateforme  
(permet au transporteur d'identifier le colis à retirer en boutique)
+ **order_id** (optional, string) : ID commande interne à votre plateforme

### Voir les détails d'un book-delivery [PUT]

+ Request (application/json)

            {
                "api_key": "3025688655a161aeb167b7b33f03c013",
                "delivery_id": 1234,
                "order_ref": "R10390",
                "order_id": "987663"
            }


+ Response 201 (application/json)

                {
                    "response":{
                        "confirmed": true
                    }
                }

# Deliveries API Root [/deliveries]
